# Describes the format for available component services

set_general_poe_limit:
  name: Set the PoE power limit
  description: Sets the system PoE power limit.
  fields:
    mac_address:
      name: MAC Address
      description: The MAC address of the switch.
      example: "11:22:33:AA:BB:CC"
      required: true
      selector:
        text:
    power_limit:
      name: Power limit
      description: New system PoE power limit.
      required: true
      default: 30.0
      example: 49.5
      selector:
        number:
          min: 1.0
          max: 1000
          step: 0.1
          unit_of_measurement: W

set_port_poe_settings:
  name: Set PoE settings for a specific port
  description: Sets PoE settings for a specific port.
  fields:
    mac_address:
      name: MAC Address
      description: The MAC address of the switch.
      example: "11:22:33:AA:BB:CC"
      required: true
      selector:
        text:
    port_number:
      name: Port number
      description: Target port number.
      required: true
      example: 1
      default: 1
      selector:
        text:
    enabled:
      name: Enable PoE
      description: Enable PoE on the specified port.
      required: true
      example: true
      default: true
      selector:
        boolean:
    priority:
      name: PoE port priority
      description: PoE priority of the specified port.
      required: true
      example: Middle
      default: Middle
      selector:
        select:
          options:
            - "High"
            - "Middle"
            - "Low"
    power_limit:
      name: PoE power limit
      description: PoE power limit of the specified port.
      required: true
      example: Auto
      default: Auto
      selector:
        select:
          options:
            - "Auto"
            - "Class 1"
            - "Class 2"
            - "Class 3"
            - "Class 4"
            - "Manual"
    manual_power_limit:
      name: Manual PoE power limit
      description: Manual PoE power limit of the specified port.
      required: false
      default: 10
      selector:
        number:
          min: 0.1
          max: 30
          step: 0.1
          unit_of_measurement: W